spring:
  datasource:
    username: root
    password: ok
    url: jdbc:mysql://192.168.1.101:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.suqianbft: info
  file:
    name: log/log.log
server:
  port: 8081